const PAGE_TRANSITION_PHASE_MS = 200;
const PAGE_TRANSITION_TOTAL_MS = PAGE_TRANSITION_PHASE_MS * 2;

export const PAGE_TRANSITION_TIMING = {
  phase: `${PAGE_TRANSITION_PHASE_MS}ms`,
  phaseMs: PAGE_TRANSITION_PHASE_MS,
  total: `${PAGE_TRANSITION_TOTAL_MS}ms`,
  totalMs: PAGE_TRANSITION_TOTAL_MS,
} as const;
